### PR TITLE
[Bounty] Table fiend component

### PR DESCRIPTION
**Pull request by ChungusGamer666**
# About The Pull Request

Completes bounty https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/issues/278
With this component, any living mob can crawl under tables as long as they are lying down.

## Why It's Good For The Game

I am being paid.

## A Port?

No, i am the god of all men.

## Changelog

:cl:
add: Crawling under tables
/:cl:

### CODE REVIEW

**Comment by UntoldTactics** [comment]
based

**Comment by ChungusGamer666** [comment]
merge this shit already

**Comment by BongaTheProto** [comment]
When glass table fix

**Comment by ChungusGamer666** [comment]
> When glass table fix

when you pay me or when i feel like it

**Comment by ChungusGamer666** [comment]
to be fair i got paid already so i dont care if this is merged or not anymore #thuglife

**Comment by ChungusGamer666** [comment]
I will not maintain this PR anymore, i will close it because bonga refuses to merge it. 👍

**Comment by ChungusGamer666** [comment]
my brother in christ open another PR if you want it, **i've made it clear i will not be maintaining this and you refuse to merge it**

**Pull request closed without merging**
