### PR TITLE
New lavaland ghostrole - Wandering Hermit. Ghostroles can be spawned with additional language from Speech Preferences.

### PR DESCRIPTION
**Pull request by dragonbird13**
## About The Pull Request

New location for lavaland survivalists - Abandoned Shelter (lavaland_surface_abandoned_shelter.dmm) and Wandering Hermit ghostrole. Appearance loader bugfixes.

## Why It's Good For The Game

Its alternative lavaland hermit but more oriented on staying at lavaland instead of returning to station.

## A Port?

Nope. Map is completely by Dragonbird13 as well as my idea.

## Changelog
:cl:
add: New location - Abandoned Shelter
add: New lavaland ghostrole - Wandering Hermit
fix: Fixed missing second language when player loaded appearance for ghostrole
/:cl:

lavaland_AbandonedShelter

### CODE REVIEW

**Comment by BongaTheProto** [comment]
This is pretty neat, though if the added objects and procs could be modularized into the modular_eros folder it would be amazing

**Comment by dragonbird13** [comment]
> This is pretty neat, though if the added objects and procs could be modularized into the modular_eros folder it would be amazing

Okay, I'll see what I can do! I apologize if I break something, cuz this is my second commit ever

**Comment by BongaTheProto** [comment]
Yeah it's alright, it looks cool! just make sure that new declared object/procs/etc or added sprites and/or content are modularized into that folder as long as it's possible when you make a pr

**Comment by BongaTheProto** [comment]
closed?

**Comment by dragonbird13** [comment]
> closed?

Aaaarghhh. I do not know how to make changes into pulls, life did not prepare me for this. aaaaaaa

**Comment by BongaTheProto** [comment]
> > closed?
> 
> Aaaarghhh. I do not know how to make changes into pulls, life did not prepare me for this. aaaaaaa

Oh, that's simple actually! just push commits into the branch your pr is tracking, it'll work as long as the pr is open or draft i think

**Comment by BongaTheProto** [comment]
Anything else you'd like to add or is it ready to be merged now?

**Comment by dragonbird13** [comment]
> Anything else you'd like to add or is it ready to be merged now?

Its ready! Thank you for help

**Comment by BongaTheProto** [comment]
> > Anything else you'd like to add or is it ready to be merged now?
> 
> Its ready! Thank you for help

You're welcome! reach me on discord if you need anything ^^

**Pull request merged**
