### PR TITLE
New eye type

### PR DESCRIPTION
**Pull request by lolman65**
## About The Pull Request

Adds third eye, a way to have special eyes

## Why It's Good For The Game

more customization good

## A Port?

noo?

## Changelog
:cl:
add: Added new thing
code: changed some code

/:cl:

### CODE REVIEW

**Comment by lolman65** [comment]
whoops.. is that was deleted?

**Comment by lolman65** [comment]
fixed

**Comment by lolman65** [comment]
lemme redo pr now i got it fixed.

**Comment by lolman65** [comment]
> image

i added it back in, as it should be

**Comment by NullFag** [comment]
image
new file
image
vs old file

**Comment by lolman65** [comment]
> image new file image vs old file

ah.. lemme fix then

**Comment by lolman65** [comment]
ok... i think its correct now?

**Comment by NullFag** [comment]
It will be correct when it will stop showing that icon state as modified.
Also git flipped the two images around in the last comment.

**Comment by lolman65** [comment]
ah, ok, i think.. i got it this time. weh.

**Comment by lolman65** [comment]
fixed

**Pull request merged**
