### PR TITLE
[BUG FIX] Implant avalibility

### PR DESCRIPTION
**Pull request by SpookyTheFox**
# About The Pull Request
Fixes availability of the genital fluid and slave implants.

## Why It's Good For The Game
These were both in the code but not able to be researched or printed. Fixing things is good for the game.

## A Port?
No, this stuff was already here from other pull requests.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
fix: fixed in character availability of the gfluid and slave implants.
/:cl:

### CODE REVIEW

**Comment by SpookyTheFox** [comment]
Did a full re-download, recompile, and local test. Works.
My code contained here does not runtime.
However. There are run times in the base implant code. The implant works still, but fixing those runtimes is outside the scope of this PR.
I might take a swing at that later, I don't know exactly how to fix those right now.

**Comment by BongaTheProto** [comment]
> Did a full re-download, recompile, and local test. Works. My code contained here does not runtime. However. There are run times in the code for the implant itself. The implant works still, but fixing those runtimes is outside the scope of this PR. I might take a swing at that later, I don't know exactly how to fix those right now.

what are the runtimes?

**Comment by SpookyTheFox** [comment]
> > Did a full re-download, recompile, and local test. Works. My code contained here does not runtime. However. There are run times in the code for the implant itself. The implant works still, but fixing those runtimes is outside the scope of this PR. I might take a swing at that later, I don't know exactly how to fix those right now.
> 
> what are the runtimes?

It coughed up all this when I clicked the implant initially. The items are because I'm a bluespace tech, it will probably do that with anything.

```
[12:50:29] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:29] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:30] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,64,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:30] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,64,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:30] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:31] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:31] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:32] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:32] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:32] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:33] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:33] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:34] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:34] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:34] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[12:50:35] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
```

Then, after choosing a reagent, it did this:
```
[12:52:36] Runtime in implant_gfluid.dm,66: Cannot execute null.del reagent().
  proc name: activate (/obj/item/implant/genital_fluid/activate)
  usr: urocyon/(Hailey Bowchiew)
  usr.loc: (Central Primary Hallway (46, 63, 2))
  src: the genital fluid implant (/obj/item/implant/genital_fluid)
  src.loc: null
  call stack:
  the genital fluid implant (/obj/item/implant/genital_fluid): activate("action_button")
  the genital fluid implant (/obj/item/implant/genital_fluid): ui action click(Hailey Bowchiew (/mob/living/carbon/human), Activate (/datum/action/item_action/hands_free/activate))
  Activate (/datum/action/item_action/hands_free/activate): Trigger()
  Activate (/atom/movable/screen/movable/action_button): Click(null, "mapwindow.map", "icon-x=17;icon-y=12;left=1;scr...", 0, null)

```

**Comment by SpookyTheFox** [comment]
> > Did a full re-download, recompile, and local test. Works. My code contained here does not runtime. However. There are run times in the code for the implant itself. The implant works still, but fixing those runtimes is outside the scope of this PR. I might take a swing at that later, I don't know exactly how to fix those right now.
> 
> what are the runtimes?

It immediately began spamming the following over and over, a couple dozen times:
```
[12:50:34] Runtime in human.dm,75: undefined variable /obj/item/gun/energy/pulse/var/air_contents
  proc name: get status tab items (/mob/living/carbon/human/get_status_tab_items)
  src: Hailey Bowchiew (/mob/living/carbon/human)
  src.loc: the floor (46,63,2) (/turf/open/floor/plasteel)
  call stack:
  Hailey Bowchiew (/mob/living/carbon/human): get status tab items()
  Stat Panels (/datum/controller/subsystem/statpanels): fire(0)
  Stat Panels (/datum/controller/subsystem/statpanels): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)

```

When I selected a fluid, it then did this one, just once.
```
[12:52:36] Runtime in implant_gfluid.dm,66: Cannot execute null.del reagent().
  proc name: activate (/obj/item/implant/genital_fluid/activate)
  usr: <myckey>/(Hailey Bowchiew)
  usr.loc: (Central Primary Hallway (46, 63, 2))
  src: the genital fluid implant (/obj/item/implant/genital_fluid)
  src.loc: null
  call stack:
  the genital fluid implant (/obj/item/implant/genital_fluid): activate("action_button")
  the genital fluid implant (/obj/item/implant/genital_fluid): ui action click(Hailey Bowchiew (/mob/living/carbon/human), Activate (/datum/action/item_action/hands_free/activate))
  Activate (/datum/action/item_action/hands_free/activate): Trigger()
  Activate (/atom/movable/screen/movable/action_button): Click(null, "mapwindow.map", "icon-x=17;icon-y=12;left=1;scr...", 0, null)

```

**Pull request merged**
