### PR TITLE
Lucky's first PR

### PR DESCRIPTION
**Pull request by SpaceCat404**
# About The Pull Request

This is a small, baby steps pull request by me. It is my first ever pull request, my first time uploading to GitHub and my first time coding with BYOND. I was curious about contributing and now I'm getting hands on experience. I think that's the biggest benefit of this PR. 

This PR adds a new language for feline characters (Nyanese), a new title for captains (Catpain) and a new junkfood item (Sunflower Seeds) which can be grabbed at any snack vendor.

Screenshot (126)
Screenshot (123)
Screenshot (125)
Screenshot (124)

Most of the code is just copies and reskins of other code, so there's very little risk of breaking anything.

This is my first time ever doing any of this, so please feel free to reach out with pointers. I'm Karro "Lucky" Glowrra on the Splurt Discord.

## Why It's Good For The Game

This is a relatively minor PR so the effects on the game will be minimal, minimal but positive.

A new language will allow players to better express themselves and their character concepts, a new title will let captain players have another choice of expression and a new snack vending machine item will slightly increase the longevity of vending machines before they need to be restocked, while not making the chef obsolete.

In addition, having my first PR implemented would do wonders for my morale and push me to continue coding and contributing! It'd be a great first step.

## A Port?

No.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Old Glory sunflower seeds, a junk food available in snack machines.
add: "Catpain" title for Captain job.
add: Nyanese (feline) language.
/:cl:

### CODE REVIEW

**Comment by SaraSayomi** [comment]
Make sure you add a empty line at the end of every file, don't actually know why but it's the standard.

**Comment by SaraSayomi** [comment]
Also on that note none of this is modular, please make it so.

**Comment by SpaceCat404** [comment]
> Also on that note none of this is modular, please make it so.

Hey Sara, I've added the lines to the end of all the files, but I'm a bit confused on what you mean by 'modular'? do you mean placing all of my changes under the modular_splurt folder? I'll redraft and reupload when it's good.

**Comment by SaraSayomi** [comment]
Conversation continues on the discord, so others know I already saw this

**Pull request closed without merging**
