### PR TITLE
[Bounty] Adds cuddling

### PR DESCRIPTION
**Pull request by ChungusGamer666**
# About The Pull Request

Completes bounty https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/issues/266

## Why It's Good For The Game

I don't give a shit i need money broke

## A Port?

i made this myself i am so good

## Changelog

:cl:
add: added cuddling interactions
/:cl:

### CODE REVIEW

**Comment by BongaTheProto** [comment]
I'm going to cuddle you :3

**Comment by ChungusGamer666** [comment]
> I'm going to cuddle you :3

mailbox

**Comment by ChungusGamer666** [comment]
someone else did this i lost about 15 minutes of my life

**Comment by BongaTheProto** [comment]
wait who

**Comment by ChungusGamer666** [comment]
nvm he's gonna pay me i guess #thuglife

**Comment by toastywaffelz** [comment]
cringe check!

*cutely caves your skull with a brick*

**Pull request merged**
