### PR TITLE
Improves the visual design of the Slaver antag hideout & shuttle

### PR DESCRIPTION
**Pull request by zydras**
# About The Pull Request

This PR modifies the visual look of the Slaver hideout and the Slaver shuttle while keeping most of its existing assets. This helps make the hideout feel more like an actual hideout than a copy-paste of a syndicate base.

The shuttle itself:
Screenshot (1455)

The newly revamped base:
Screenshot (1452)

## Why It's Good For The Game

This helps differentiate Slavers from Syndicate agents visually, all while maintaining a certain visual aspect. Also uses its own tileset that's not a snowy landscape. It's mostly flavor-oriented changes that help Slavers feel like their own unique thing.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
expansion: Completely remodeled the Slaver Hideout and its shuttle for improved Slavery ambience.
/:cl:

### CODE REVIEW

**Comment by Turtle567** [comment]
So cool how the slavers somehow got Stillwater to not freeze in the middle of space on an asteroid, truly amazing.

**Comment by zydras** [comment]
> So cool how the slavers somehow got Stillwater to not freeze in the middle of space on an asteroid, truly amazing.

Fun fact! While the turf is under asteroid, it still naturally comes with a normal atmosphere.

**Comment by Turtle567** [comment]
Oh so it's like a hollowed out asteroid, pretty cool, I like it

**Comment by Crowbar764** [comment]
Hey @zydras !

You've done an amazing job bringing the style to life, I think it's a lovely improvement on the aesthetics. I am a little worried about how tight and crampt the design is, especially when considering people need to drag cuffed, unwilling people through 1 tile wide chokes, but maybe it will work out ok, we'll see in the test-runs. 

Here are some snags I picked up on with a quick look:

<details>
  <summary>Cell Shutters</summary>
The cell buttons open / close the wrong cell's windows. Double check their variables all are correct!

image
</details>

<details>
  <summary>Windows</summary>
Windows for some reason are breakable in some places and unbreakable in others.

Also some of the windows don't merge properly.

image
image

</details>

<details>
  <summary>Guide</summary>
The paper guide needs updating now that the area has changed. (Or just write a better guide!)

image
</details>

<details>
  <summary>Shuttle Windows</summary>
As far as I can tell, there is no button for these window shutters. They do have a remote control ID set so not sure if this is intentional or just something forgotten.

I tested opening the shutters myself and the turrets shoot INTO the ship to try and attack the brigged slaves. So going to assume these are just for decoration and aren't meant to open.

image
</details>


<details>
  <summary>Shuttle Cockpit</summary>
There's no shuttle computer! You need two consoles to fly shuttles like these:


A 'navigation computer' which sets the shuttle destination (you have this).
And a /obj/machinery/computer/shuttle/slaver (you don't have this). This actually moves the shuttle.


Additionally you have a security records computer in there which slavers don't have access to use.
image
</details>

<details>
  <summary>Decals</summary>
LEFT is the map editor. RIGHT is in-game.
The arrow decals face the wrong way.

Also decals do NOT work at all on shuttles, so you can go ahead and just delete any shuttle decals.

image
</details>

Other than that I think it's pretty good!

**Comment by zydras** [comment]
Hey, thanks for the feedback @Crowbar764 !! I'll get to those changes. I swear I caught them in testing but it looks like I goofed up. I swear I forgot something about the shuttle computer but couldn't figure it out. Thanks!
The shuttle's slave holding pen is meant to have to shutters toggle, it's mostly a visual thing to show the ship being, well, 'Remodeled'. I also learned the hard way that the shuttle indeed doesn't allow for floor details... [sobs]

**Comment by zydras** [comment]
Oh! I realize these are redundancies from when I tried to give the slaver hideout the Layenia cloud chasm type of turf, but sadly it didn't work. I'll remove them!

**Comment by Crowbar764** [comment]
@zydras the APC is so synthetic players can recharge themselves haha

**Comment by zydras** [comment]
@Crowbar764 fixed!

**Pull request merged**
