### PR TITLE
Barely legal ports

### PR DESCRIPTION
**Pull request by BongaTheProto**
# About The Pull Request
adds a few cool character sprites and some sushis to the game, as well as some clothes

## Why It's Good For The Game
free content is free content

## A Port?
https://github.com/Bubberstation/Bubberstation/pull/207
https://github.com/Bubberstation/Bubberstation/pull/129

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: adds runner jackets
add: adds a bunch of new horns for character customization
add: adds a few more variants of sushi
/:cl:

### CODE REVIEW

**Comment by Scuhf-git** [comment]
Weird to remove the accrediting comments for the sprite creators but go off.

**Comment by Scuhf-git** [comment]
Anyway, the jackets are by Kan3 and the horns are by yourself truly (me).

**Comment by kaylexis** [comment]
If you are going to import sprites and items from another server, then you should at least keep in the credit of who made the sprites, it's awful seeing my stuff be ported and not credited. 
Context: I am the one who sprited the jackets.

**Comment by Scuhf-git** [comment]
@BongaTheProto have time to change the whole PR name then to also put two peoples names in for credit?

If you don't know how I can tell you; you click on those three little dots on the top right hand corner and click the "edit" button, then you'd type the spriters names in that you've removed originally.

**Pull request merged**
