### PR TITLE
Ghost Cafe Revamp [W.I.P] (don't merge please)

### PR DESCRIPTION
**Pull request by abit-slutty**
# About The Pull Request
Ghost Cafe Revamp, mostly just testing to see if I did this right, maintainers if I am attempting to merge the wrong thing let me know. (example: if I wasn't suppose to delete the map LOL)

## Why It's Good For The Game
Current Cafe sucks, this one is cooler.

## A Port?
Kind of, it's skyrats cafe ported to our codebase +- some tiles since we have different sprite names, couldn't find the skyrat PR but can edit this if someone can provide.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: new centcom map 
del: old centcom map
note: it's the same map just with cafe deleted and new cafe added
/:cl:

### CODE REVIEW

**Comment by SmiLeYre** [comment]
Прикол.

**Comment by BongaTheProto** [comment]
Did you keep the vr spawners from our actual ghost cafe in the new one?

**Comment by Satile1** [comment]
Here's a screenie of the PR's map -


Looks like the shuttle import marker got killed, probably need that back. Also what about the beach resort from Skyrat's current one! We can do cozier..

[Skyrat's current beach](https://gyazo.com/52c194bb0a43f40b137554850c2e1660)

**Comment by abit-slutty** [comment]
> Did you keep the vr spawners from our actual ghost cafe in the new one?

This is still WIP, it's using our actual ghost cafe sleepers not anything else.

**Comment by abit-slutty** [comment]
> Here's a screenie of the PR's map - 
> 
> Looks like the shuttle import marker got killed, probably need that back. Also what about the beach resort from Skyrat's current one! We can do cozier..
> 
> [Skyrat's current beach](https://gyazo.com/52c194bb0a43f40b137554850c2e1660)

Thanks for the screenie, also NOOOOOO I PORTED THE WRONG MAP PART AAAAAAAAAAAAAAAAAAAAAAAAA, I'll add their current beach area in a bit, as for the shuttle import marker I'm going to need to know where it /was/ so I can avoid murdering it.

**Pull request closed without merging**
