### PR TITLE
Adds the Rapid Disrobe Implant

### PR DESCRIPTION
**Pull request by LeDrascol**
# About The Pull Request
Adds a new implant for nudist quirk users that triggers the LPD drink effect, lunching away all clothing items.

Quirk holders automatically gain this implant. Other crew members can buy it from a hacked kinkmate vending machine.

action_rapid_disrobe

## Why It's Good For The Game
Minor quality of life for quirk holders. This is mostly for comedic purposes.

## A Port?
No.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
add: Added implant: Rapid Disrobe
tweak: Nudists now start with a Rapid Disrobe implant
/:cl:

### CODE REVIEW

**Comment by BongaTheProto** [comment]
Actually... It would probably be better to port over the explode from clothes interaction which basically removes all of your clothes at once, and add it as a lewd verb rather than an implant and it'd be available for everyone. It would essentially use the same code as the liquid panty dropper

**Comment by LeDrascol** [comment]
> removes all of your clothes at once

I made a second implant for this, but the results were so catastrophic (and comedic) that I didn't think it would make a reasonable addition.

**Comment by BongaTheProto** [comment]
> I made a second implant for this, but the results were so catastrophic (and comedic) that I didn't think it would make a reasonable addition.

even using code similar to the liquid panty dropper? I mean that's pretty much what it does

**Comment by LeDrascol** [comment]
> using code similar to the liquid panty dropper? 

I've made PR https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/675 to facilitate such an interaction. This item can be updated to reuse that code.

**Comment by LeDrascol** [comment]
> add it as a lewd verb rather than an implant and it'd be available for everyone

This is an interesting idea, but would devalue the effects of the original drink and potentially oversaturate the station in comedic antics. The implant is a restricted-stock item to limit how many people will randomly find it, and maintain it's semi-unique value.

**Comment by BongaTheProto** [comment]
> This is an interesting idea, but would devalue the effects of the original drink and potentially oversaturate the station in comedic antics. The implant is a restricted-stock item to limit how many people will randomly find it, and maintain it's semi-unique value.

I suppose so, though I mention it because we used to have something like that in our old codebase but it didn't made clothes be thrown around in the air, just stay in the tile. Maybe the verb could just throw the clothes in the tile and the implant and such makes them expplode?

**Comment by LeDrascol** [comment]
> Maybe the verb could just throw the clothes in the tile and the implant and such makes them explode?

If the goal is to keep the current implant behavior _and_ add a verb, then the verb addition could be made in a separate pull request. I'm not yet familiar with adding new verbs.

**Pull request merged**
