### PR TITLE
New quirk: Rad Fiend

### PR DESCRIPTION
**Pull request by LeDrascol**
# About The Pull Request
Adds the ~~Lead Blooded~~ Rad Fiend quirk, which renders a user ~~immune~~ highly resistant to radiation. The user also gains a customizable glow effect, with options to change the outline's color and thickness at will.

This quirk cannot be used with radiation immune characters, such as with round-start undead races.

quirk_radfiend_glow

## Why It's Good For The Game
Allows greater character customization, and increases the number of positive quirks to choose from.

## A Port?
No.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
add: Added positive quirk: Rad Fiend
/:cl:

### CODE REVIEW

**Comment by zeroisthebiggay** [comment]
i can feel like seeing people glowing green is going to sow a whole lot of panic before realizing it's just some snowflake quirk and they're not `actually` a walking ball of radiation

also

> This quirk cannot be used with radiation immune characters, such as with round-start undead races.

why
if a skeleton wants to glow green let the skeleton glow green

**Comment by LeDrascol** [comment]
> i can feel like seeing people glowing green is going to sow a whole lot of panic before realizing it's just some snowflake quirk and they're not `actually` a walking ball of radiation

Medical HUDs and scanners will indicate if a target has actual radiation.

> why if a skeleton wants to glow green then let the skeleton glow green

The glow comes is based on [Cherenkov radiation](https://en.wikipedia.org/wiki/Cherenkov_radiation), and implies that the holder is radioactive. Targets that cannot become irradiated cannot glow.

**Comment by zeroisthebiggay** [comment]
> The glow comes is based on [Cherenkov radiation](https://en.wikipedia.org/wiki/Cherenkov_radiation), and implies that the holder is radioactive. Targets that cannot become irradiated cannot glow.

41baWGWOGcL _AC_SY580_

you lie

**Comment by LeDrascol** [comment]
> [picture of skeletons]
> 
> you lie

You may be confusing this with [phosphorescence](https://en.m.wikipedia.org/wiki/Phosphorescence), which is not covered by this PR.

**Pull request merged**
