### PR TITLE
Add Bluespace Light Replacer to Science protolathe

### PR DESCRIPTION
**Pull request by LeDrascol**
# About The Pull Request
Adds a science departmental flag to bluespace light replacers, allowing the Science team to print them.

## Why It's Good For The Game
Lights on the station break periodically, and replacing them manually is tedious. Service or engineering can fix this, but usually don't.

In the current map layouts; The service protolathe is difficult to find, and often even missed by service members. Users are often required to ask the bartender or chef for a light replacer, which they may be unable to assist with unless provided further guidance.

### To quote some users from the Discord:

_No comms on an RP server or all the lights exploded and the janitor isn't replacing them because they've been swallowed by the engineering borg who is also not replacing the lights_
\- Broken Water Dispenser (BoneSeer#7486)

_We will be on 24/7 light bulb exploding conga_
\- Broken Water Dispenser (BoneSeer#7486)

_What we need is 10 service borgs because the most common occurrence on the station is ******* electrical storm and all the lights explode_
\- Broken Water Dispenser (BoneSeer#7486)

>lights explode
>walk into xenobio
>the lights explode
>living life in my hermit pad
>THE LIGHTS EXPLODE
>LAND THE WHITE SHIP ON STATION Z LEVEL FOR TWO WHOLE SECONDS
>THE LIGHTS ******* EXPLODE

\- Broken Water Dispenser (BoneSeer#7486)

>Lights explode
>Oops all scrubber reagents
>Lights explode
>Greytide on the medbay
>Anomaly
>Lights explode
>Anomaly
>Anomaly
>Level 7 biohazard
>TF2 DRUMROLL
>Lights explode

\- Voltz (Neun#3470)

## A Port?
No.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: Added Bluespace Light Replacer to the Science protolathe
/:cl:

### CODE REVIEW

**Comment by BongaTheProto** [comment]
Members of staff are wondering if instead of making it available for all departments it can be made so that only science is added, that way players can go there and ask for one

**Comment by LeDrascol** [comment]
> made so that only science is added

This is a reasonable suggestion. 

As a possible alternative; To encourage crew to interact with science, and to maintain theme, we could give them shared or exclusive access to a _bluespace_ light replacer instead of the normal version.

**Comment by BongaTheProto** [comment]
> we could give them shared or exclusive access to a _bluespace_ light replacer instead of the normal version.

This is fine as long as it goes in a high tech tier

**Comment by LeDrascol** [comment]
> This is fine as long as it goes in a high tech tier

I submitted a port of the Bluespace Light Replacer (from Bee) upstream to Citadel. Until it reaches this codebase, the PR can remain a draft.

**Pull request merged**
