### PR TITLE
[MOSTLY MODULAR] Adds bird-related flavor features

### PR DESCRIPTION
**Pull request by NopemanMcHalt**
# About The Pull Request
Added a few emotes and new language related to the bird-people. I am not creative regarding the language, so it's just peeps and beeps.

## Why It's Good For The Game
I like birbs. Also suggestion 5590.

## A Port?
Nope.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl: Anonymous
add: Added *coo, *facewing and *ruffle (wings' ruffle).
add: Added Avian language. It's quite basic, though.
/:cl:

### CODE REVIEW

**Comment by BongaTheProto** [comment]
apparently there's a runtime with language sprites
image

**Comment by NopemanMcHalt** [comment]
> apparently there's a runtime with language sprites (snip)

Yeah, both `nulls` even without sprites are considered as duplicate for sprite-sheet code. I just changed our `null` icon into named debug icon `"whar"`, so should be good now.

**Comment by BongaTheProto** [comment]
pls fix the merge conflicts

**Comment by NopemanMcHalt** [comment]
> pls fix the merge conflicts

Done!

**Pull request merged**
