### PR TITLE
Who let the dogs out? Also brig medic mapping fixes part 2

### PR DESCRIPTION
**Pull request by Gr33d-y**
Updates brig medic areas to have cells for their defib along with operation tables and computers. Also adds a bark box to every map minus box for now.

Moves a few things around in the brig doc areas to fit all the new stuff as well as an underused bark box for every map as I think we only have it on one map.

## Why It's Good For The Game

The brig medics need love too as their workspaces are outdated most of the time. Also the bark box is kinky as fuck~

## A Port?

nope, just mapped this.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Cells, surgery tables and surgery computers to every brig medic area as well as a bark box to every map minus box station for now.
/:cl:

### CODE REVIEW

**Comment by Gr33d-y** [comment]
seems like there was a conflict due to the fact we already have a box station update in the works, the box station barkbox has been removed from this update.

**Comment by Gr33d-y** [comment]
added tramstation as well to be worked on as we are unsure of its playability at this time.

**Comment by BongaTheProto** [comment]
> added tramstation as well to be worked on as we are unsure of its playability at this time.

Actually, Tram isn't like the other maps since it actually needs me to add some code and new functions with rust_g, so I'd rather add it myself later or have it as a separate pr, not here

**Comment by Gr33d-y** [comment]
Fair nuff, ill remove it for now

**Pull request merged**
