### PR TITLE
Prevent holodeck griefing

### PR DESCRIPTION
**Pull request by LeDrascol**
# About The Pull Request
Replaces three holodeck modules with harmless variants.
- Atmospheric Burn Test => CRITICAL ERROR
- - Uses a harmless binary floor
- Wildlife Simulation
- - Uses a basalt floor with funclaws, and a protective pit to prevent the mob from destroying the terminal
- Anthophila
- - All bees are friendly

## Why It's Good For The Game
Restricted holodeck modules can cause unwanted - sometimes unintentional - griefing to the dorms area. This change makes the relevant modules harmless.

## A Port?
No.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
tweak: Replaced three dangerous holodeck modes with harmless alternatives
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
Haram 👎 

If there are ever antags on the station, they deserve the funny bees or carp scenes.

I’m ok with the plasma fire one being replaced though.

**Comment by LeDrascol** [comment]
> If there are ever antags on the station, they deserve the funny bees or carp scenes.

The dorms are consecrated ground protected by our corporate overlords at NanoTransen under punishment of a funny noise. For anything antagonistic to be allowed with the holodeck, it would need to be moved elsewhere.

**Comment by KathrinBailey** [comment]
This is a bad way to do something that isn't really needed anyway, given we have so much dorms protection that not only do we have tiny fans to nullify plasma floods, we have Hilbert's Hotel for people to do stuff in risk-free.

Do not change the mob spawners or the gasmix tile. Create a new tile and mob spawner, and then change the holodeck maps (top right of the CC Z level).

This is like when skyrat made red decal corners blue.

**Comment by LeDrascol** [comment]
Closing this due to community feedback.

**Pull request merged**
