### PR TITLE
speen moment

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Added spin view verbs.

## Why It's Good For The Game

Yeah. (I'm paying him for this -Bonga)

## A Port?

I stole the code from vorestation

## Changelog
:cl:
add: added speeen (not the verb, like screen speen)
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
mosley better pay me my 3 bucks

**Comment by BongaTheProto** [comment]
wasn't it 3

**Comment by ChungusGamer666** [comment]
> wasn't it 2

inflation

**Comment by ChungusGamer666** [comment]
nvm this wont work

**Pull request closed without merging**
