### PR TITLE
adds pacification bans

### PR DESCRIPTION
**Pull request by NullFag**
## About The Pull Request

See title. Also fixes emote/OOC ban messages.

## Why It's Good For The Game

You tell me.

## A Port?

Your mother.

## Changelog
:cl:
admin: adds paci bans
/:cl:

### CODE REVIEW

**Comment by NullFag** [comment]
By the way, I can't make it not error the linter. It does work perfectly though.

**Comment by BongaTheProto** [comment]
I can't really accept a pr with linter errors

**Comment by NullFag** [comment]
> By the way, I can't make it not error the linter. It does work perfectly though.

Scratch that.

**Comment by BongaTheProto** [comment]
So whenever you mess with the database you gotta as well put what queries shall be run in the current database to update it to the latest schema. This is what the database changelog txt is for

**Pull request merged**
