### PR TITLE
Syndie base shit

### PR DESCRIPTION
**Pull request by NatSCP**
# About The Pull Request

Updates Syndie listening post to give Syndie comms agent shit to do (other than, y'know, comms agent stuff)

## Why It's Good For The Game

makes Syndie base not shit

## A Port?

no lol

## Changelog

:cl:
add: John Syndicate
qol: Kinkmate, Clothes Vendor, Ore Silo and ORM, Protolathe board, some other shit I probably forgot
tweak: Replaced Circuitry with Botany
/:cl:

### CODE REVIEW

**Comment by NatSCP** [comment]
Big goldfish

**Comment by BongaTheProto** [comment]
>  Big goldfish

Best goldfish, he will swim to the moon 🐟

**Comment by NatSCP** [comment]
By allah I shall die standing

**Comment by NatSCP** [comment]
The horses are running mile after mile
Freedom is dear to us
Through the slot of the machine gun
I am looking for the enemy in the dust

Mother anarchy loves her sons
Mother anarchy will not sell us out
With a rain of lead we will embrace our enemy
Mother anarchy is with us

I will heat my knife in the fire
As I let my enemy come closer
I am not sorry for anything in battle
I have nothing to grieve over

Mother anarchy loves her sons
Mother anarchy will not sell us out
With a rain of lead we will embrace our enemy
Mother anarchy is with us

I only rejoice at the slaughter
By the strength of my friend
I can see calmly
Nothing but my dead enemy

Mother anarchy loves her sons
Mother anarchy will not sell us out
With a rain of lead we will embrace our enemy
Mother anarchy is with us (x2)

With a rain of lead we will embrace our enemy
Mother anarchy is with us (x2)

Mother anarchy is with us (x3)

**Comment by NatSCP** [comment]
I CANNOT BE SILENCED.

**Comment by NatSCP** [comment]
https://user-images.githubusercontent.com/102256604/162643374-6433ec41-31d0-470d-aae7-75bffa937d7a.mov

**Comment by NatSCP** [comment]
https://user-images.githubusercontent.com/102256604/162643398-45b8f296-ff57-43e7-9686-0ebb622d77dc.mp4

**Pull request merged**
