### PR TITLE
Peacekeeper Redux

### PR DESCRIPTION
**Pull request by AshTheDerg**
# About The Pull Request

Readds the Peacekeeper Role, an RP-centric Security Role for newbies, as well as a few smaller things

## Why It's Good For The Game

Peacekeepers. Sec Pouches. Deputy Badges. Fabricatable Badges. And a less-useless HoP Tablet.

## A Port?

No

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Peacekeepers
add: Security Pouches
add: Deputy Badges
tweak: Badges except Holo can be fabricated in a Sec TechFab
tweak: Removed Hypo and Baton from Peacekeepers
tweak: Gave Peacekeepers a Taser
fix: Command Tablets now come with a secondary Card Reader
/:cl:

### CODE REVIEW

**Comment by AshTheDerg** [comment]
> hahahaha what the fuck?
> 
> Giving peacekeepers an instant-inject hypospray which takes large vials? The same one that the CMO gets? Instead of the doctors?
> 
> Giving them better armor than regular security, a telebaton and basically the same access?
> 
> Giving them access to instant-inject armor-piercing pax and tiring solution?
> 
> Literal powercreep PR.
> 
> To help put this into perspective.
> 
> Peacekeepers by your own items are DEPUTIES. They have better gear in some cases than even ERT, this is not okay.

Actually, the Hypo does NOT take other vials.

Brig Doc gets a T-Baton, nobody fucking complains.

PK Borgs get the same Hypo

**Comment by Gr33d-y** [comment]
nah, just let peace keepers have a separate role from sec, they should be the sec BEFORE the sec, if they need these things for that, fuck it, let em keep em.

**Comment by AshTheDerg** [comment]
The PK Hypo is not Armor Piercing. I made sure of that. bypass_protection = 0

As far as the Baton, why does a Brig Doc _need_ one? They're hardly Sec.

I've been thinking about swapping them from Sec pay to Civ. They only really have basic Sec access, not even Sec Equipment.

**Comment by AshTheDerg** [comment]
> > The PK Hypo is not Armor Piercing. I made sure of that. bypass_protection = 0
> > As far as the Baton, why does a Brig Doc _need_ one? They're hardly Sec.
> > I've been thinking about swapping them from Sec pay to Civ. They only really have basic Sec access, not even Sec Equipment.
> 
> They can open sec equipment lockers.
> 
> Also, the bypass_armor variable acts strangely and borg hypospray code inherently ignores some forms of armor needles do not, e.g sec vests and helmets which (usually) stop shot syringes/etc, hence the armor piercing tag.

They shouldn't be able to open the lockers. I'll have to look into that.

Honestly, considering the contents of the Hypo, and the fact it's impossible to OD anyone unless on Harm (Which they shouldn't ever be), I don't really see a problem with that.

**Pull request merged**
