### PR TITLE
Hotfix for borg tiles fucking dying

### PR DESCRIPTION
**Pull request by PurpleFenn**
# About The Pull Request
No longer a hotfix! We've fully fixed borg tiles fucking dying, woo!

## Why It's Good For The Game
Borg tiles quit fucking dying

## A Port?
Nah fam

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
del: The fucking stupidest bug ever for us engiborgs
fix: Borgs will no longer drop their floor tiles when they choose a different tile type
/:cl:

### CODE REVIEW

**Comment by LunarFleet** [comment]
Are you sure you can't just prevent the icon from changing, or fix the icon typepaths? It could be that the tiles aren't actually disappearing, but are just getting set to an invalid icon ID.

**Comment by PurpleFenn** [comment]
> Are you sure you can't just prevent the icon from changing, or fix the icon typepaths? It could be that the tiles aren't actually disappearing, but are just getting set to an invalid icon ID.

What's happening in the tile reskin code is that the tiles are getting moved to nullspace and the new tiles are getting put in the user's hand
image

I can firmly state that the tiles icon state is perfectly fine, because if we look at the cyborg subtype of the plasteel tiles, we see that there's legitimately nothing special about them.
image

You can also confirm ingame that the tiles are remaining as the cyborg subtype of plasteel tiles when you switch your tiles.
image

However if we look at what's actually happened to that, it's been deleted. It went byebye. It's still stuck in the list, causing the empty space in the module, but it just. Doesn't exist anymore. It's not in GC because of still being referenced, and won't land there until the reference is gone.
image

**Comment by LunarFleet** [comment]
Fair enough, just figured I'd mention the possibility, I know I've seen similar happen before with borgs- Borgs be funky, I know that, on polaris codebases, if you are a medical borg, and you place a beaker into a machine, you can still select the module even though the beaker is in the machine, and ejecting the beaker, and then storing the module, will return the beaker to your inventory. Shit's wack. Figured it could be something dumb like that again was all.

**Comment by PurpleFenn** [comment]
Yep, I gotchu. Was doing quite a bit of investigation before making any PR at all to make sure something like that wasn't the issue, SS13 in general is fucky like that

**Comment by PurpleFenn** [comment]
Planning for the future™:
- Re-activate the new floortile module and enable it
- In a new PR, post-merge:
  - Fix for some upgrade modules not removing their old versions

**Pull request merged**
