### PR TITLE
Adds the Emergency Vault Shuttle

### PR DESCRIPTION
**Pull request by AyyRobotics**
## About The Pull Request

Adds a new emergency shuttle that can be bought, "The Vault" or the "Emergency Vault" shuttle, for 7500 credits. Comes with reinforced walls, panic rooms, and atmospheric-resistant airlocks in a "Fresh" package.
image
image

## Why It's Good For The Game

To not only have new shuttle variety, but a shuttle that can be used to finally counter shuttle-griefers.
I know people have mentioned things like hijack objectives but considering we don't really have proper traitors with such objectives, that won't really be an issue.

## A Port?

Nope.

## Changelog
:cl:
add: Added "The Vault" Emergency Shuttle for 7500 Credits.
/:cl:

### CODE REVIEW

**Comment by AyyRobotics** [comment]
God damnit I need to convert using Map Merger, I don't even know what that is. I'll find out how to do it in like an hour or something.

**Comment by BongaTheProto** [comment]
It's a tool in the repo https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/tree/master/tools/mapmerge2
To avoid this to happen you should install the hooks in the tools>hooks folder, although I think if you run https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/blob/master/tools/mapmerge2/I%20Forgot%20To%20Map%20Merge.bat It will install them automatically and fix the map

**Comment by AyyRobotics** [comment]
Dear lord, thank you. I was almost about to actually use GitKraken, you've saved me.

**Comment by BongaTheProto** [comment]
I just pulled it and it automatically made a change on it on the repo lol, the conversion happened automatically upon pushing for some reason. Glad to help anyways :3

**Pull request merged**
