### PR TITLE
[MEMEMOTES] Adds Attorney Online emotes, changes rizz message and adds new gachimotes

### PR DESCRIPTION
**Pull request by NopemanMcHalt**
# About The Pull Request
This will add "objection", "hold it" and "take that" emotes with long cooldown, as well as option for non-verbal objection and ability to write in your own catchphrase (only in lower case though). Plus realization, nani and smirk2.
Changes rizz message to be of the Suggestion 5700 idea.
Canon event mememote added (Suggestion 5701).
~~Removes "attention", "go", "chuckle2" and "wth2" gachis~~ Adds in "sorry for what", "fucken sl\@ves" and "get your ass back here!".

## A Port?
As mentioned in the title, attorney sounds are ~~stol~~ taken from Attorney Online `[BRANCH WITHHELD]`.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl: CEO of Mememotes
add: Added attorney-flavored emotes for when you REALLY need to throw an objection: *objection, *holdit, *takethat (incl. *objection0 which is without voice. You can set custom catchphrase by writing text after the objection emotes or similar, but it will be always lower-case). Plus *realize, *nani, *smirk2, *sl@ves, *assback, *sorryfor (gachis) and *2099 (if - god forbid - a canon event happens).
tweak: *rizz message is now all about [The Look].
/:cl:

### CODE REVIEW

**Comment by NopemanMcHalt** [comment]
> Why deleting the other mememotes tho?

I felt these ones were under-utilized, though granted I don't play in US time, so I am not sure. I also can't get good feedback on what mememotes are being used, liked or not.
Indeed I used `*wth2` a lot, but felt it just me who used it.

**Comment by BongaTheProto** [comment]
> I felt these ones were under-utilized, though granted I don't play in US time, so I am not sure. I also can't get good feedback on what mememotes are being used, liked or not. Indeed I used `*wth2` a lot, but felt it just me who used it.

I mean even if they're underutilized there's no real downside to having them anyways

**Comment by NopemanMcHalt** [comment]
Fine, have them back then.

**Comment by NopemanMcHalt** [comment]
Bongooo why you have test merge on while fully merging it anyway

**Pull request merged**
