### PR TITLE
Add explanations for verb toggles in preferences

### PR DESCRIPTION
**Pull request by solarbearcub**
## About The Pull Request

Adds three spans to the character preferences menu with short explanation tooltips for the unholy, extreme and harmful verb options. 

## Why It's Good For The Game

Makes it obvious what these toggles do and doesn't crowd the UI as much as including them inline with the rest of the text.

## A Port?

No.

## Changelog
:cl:
add: explanations for unholy verb, extreme verb and harmful verb toggles in preferences.
/:cl:

### CODE REVIEW

**Comment by BongaTheProto** [comment]
Doesn't seem to be working 
image

**Comment by solarbearcub** [comment]
That's it working. Hover over the question marks, it shows via tooltip.

**Comment by solarbearcub** [comment]
That's a good point though, that it's not obvious what those question marks mean. Should maybe add `cursor: help;` to it?

**Comment by BongaTheProto** [comment]
Making them more obvious and likely to hover over would be good, yes. People keep asking what these verbs are for

**Pull request merged**
