### PR TITLE
Better sprite centering

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

your sprite gets centered good when your sprite size gets changed

## Why It's Good For The Game

good for my wallet

## A Port?

 made from scratch.

## Changelog
:cl:
tweak: Sprites don't go into walls now (I can properly satisfy my macro fetish now)
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
this is driving me mad

**Comment by BongaTheProto** [comment]
Hi mad I'm dad!

**Comment by BongaTheProto** [comment]
I'll keep this open even if it ain't getting merged yet just in case sandpoot's own one does something weird/for reference/remember the day I wasted bob's time (and gave him 3 dollar)

**Comment by ChungusGamer666** [comment]
thank you for the gold kind stranger

**Comment by ChungusGamer666** [comment]
merge confrict

**Pull request closed without merging**
