### PR TITLE
Improving the Vault Shuttle

### PR DESCRIPTION
**Pull request by AyyRobotics**
## About The Pull Request

Updates "The Vault" shuttle to a larger, improved version.
image

## Why It's Good For The Game

The original shuttle is just too small, especially in the bridge. This mostly fixes that issue, while also making it slightly safer.

## A Port?

Nope.

## Changelog
:cl:
add: Added an improved version of The Vault shuttle.
/:cl:

### CODE REVIEW

**Comment by AyyRobotics** [comment]
I did this through GitKraken, so _hopefully_ there won't be any map merge errors.

**Comment by AyyRobotics** [comment]
_God damnit._

**Comment by AyyRobotics** [comment]
Might've fixed it, going to make some light change to restart the checks.

**Comment by AyyRobotics** [comment]
God, I have no idea how to Map Merge. This might take a while.

**Comment by AyyRobotics** [comment]
Oh Christ, my bad merging luck is spreading.

**Comment by BongaTheProto** [comment]
If you installed the hooks it should automatically transform the map when you commit after editing it, idk why it didn't work when you committed it

**Comment by AyyRobotics** [comment]
Maybe I'm missing a file or something I need? I'll look into it, but for now thank you so god damn much for saving me.

**Comment by BongaTheProto** [comment]
try installing the hooks again

**Comment by BongaTheProto** [comment]
ah btw question, did you use strongdmm or just dreammaker for this?

**Pull request merged**
