### PR TITLE
[TESTMERGE ONLY] Snaxi Outpost - First Chuggening

### PR DESCRIPTION
**Pull request by IgiariValkyr**
# About The Pull Request

We all know the map Snow Taxi. Too long has it sat unloved. Abandoned. Now, we update it. It's a port of Snaxi from [Lumos Station](https://github.com/Lumos-SS13/Lumos), adjusted for our code. All departments are now locally in the same area instead of being spread out. Toxins launch is moved to the middle layer of the outpost rather than being on the top layer attached to the bottom section of the station (being incredibly far away from Science as a whole). The engine is routed to hopefully not implode when started, but the TEG and antimatter drip are also decent options.

<details><summary>Images</summary>

Top
Middle
Bottom

</details>

## Why It's Good For The Game

It's Snaxi! We all love Snaxi!

## A Port?

As stated, this is a port of Snaxi from [Lumos Station](https://github.com/Lumos-SS13/Lumos) with some edits.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.
- [x] Power and atmos actually move up and down layers.
- [x] Storms properly affect the exterior of the station (top-layer only).
- [ ] People like the map.

## Changelog

:cl:
add: SNAXI! ITS SNAXIIIIIII!

/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
Good news. Got my install of the code to work properly, so I can look the map over for real now without a test merge. Atmos and Electricity work fine between layers!

Storms stopped working unexpectedly though on the top layer. Looking into it and will push another commit.

**Comment by IgiariValkyr** [comment]
Actual final push this time. No more edits unless something is horribly wrong. Second Chuggening will be map suggestions from players once the map has had a few rounds for people to learn and get used to it.

And so people who actually look through github can see, I want to eventually do this. It's a combo of the plasma river from Icemoon and the tram from Tramstation.
<details><summary>Image</summary>
opera_2022-11-13_22-54-59
</details>

**Comment by IgiariValkyr** [comment]
**Thanks for the test round. Here's the current list of shit I have to fix.**

- [ ] For the love of fuck fix atmos this time for real
- [ ] Perma needs bio-generator and cultivator
- [ ] Better power backup for left station
- [ ] Fix infinidorm ball
- [ ] Navigation beacons
- [ ] Signs to departments
- [ ] More coat closets
- [ ] Fix access to blueshield office
- [ ] Fix hole in warehouse
- [ ] second dorm layer protected with unbreakable ice
- [ ] add colormates
- [ ] fix paramedic locker access
- [ ] add office specific Drobes
- [ ] Sec office by cargo has an engine monitor
- [ ] Color code the teleporters

**Comment by IgiariValkyr** [comment]
You probably see in the last one for the engineering post, I got rid of "power storage". It was a small 2x3 room that was only notable as a blob spawn. I turned it into a decent location for a, albeit cramped, security post for engineering.

**Comment by JerryWester** [comment]
Robotics circuit imprinter is a departmental imprinter. On most (or all) other maps, it's an unrestricted circuit imprinter.

**Comment by IgiariValkyr** [comment]
> Robotics circuit imprinter is a departmental imprinter. On most (or all) other maps, it's an unrestricted circuit imprinter.

Will be fixed.

**Comment by CheBuRek017** [comment]
image
Shuttle did a little part separation.

**Comment by Bubbadoo** [comment]
> image Shuttle did a little part separation.

That shift also had all the windows and windoors in the Med/Sci wing doubled up on the same tile, which was very odd (And in case of the windoors obnoxious as hell lol)

**Comment by CheBuRek017** [comment]
No power z-level adapter on lower mining base. Present at xenoarch though

**Comment by Bubbadoo** [comment]
image
There is gas tanks embedded in the wall inside the Telecomms and AI Access rooms, and that definitely doesn't seem right

**Comment by IgiariValkyr** [comment]
> image There is gas tanks embedded in the wall inside the Telecomms and AI Access rooms, and that definitely doesn't seem right
> 
> 02 closet in this wall too! image

These are not present in the map editor.

**Comment by IgiariValkyr** [comment]
Implimented #640

**Comment by IgiariValkyr** [comment]
Snaxi will return with a coat of green leaves and temperate climates. Be on the lookout for Jaxi Outpost: Second Chuggening.

**Pull request closed without merging**
