### PR TITLE
readds minesweeper

### PR DESCRIPTION
**Pull request by NullFag**
## About The Pull Request

Read title.

## Why It's Good For The Game

5 bucks.

## A Port?

Revert of Citadel's #15232.

## Changelog
:cl:
add: readds minesweeper
/:cl:

### CODE REVIEW

**Comment by BongaTheProto** [comment]
Uhh... this also does remove all of the problems which were the reason why it got deleted in first place, right?

**Comment by NullFag** [comment]
> Uhh... this also does remove all of the problems which were the reason why it got deleted in first place, right?

I saw no lag on my end. As for the price spam, you could already spam-play Tetris and no one saw any issue with that.

**Comment by BongaTheProto** [comment]
> > Uhh... this also does remove all of the problems which were the reason why it got deleted in first place, right?
> 
> I saw no lag on my end. As for the price spam, you could already spam-play Tetris and no one saw any issue with that.

How about everything else that was mentioned on the original pr?

**Comment by NullFag** [comment]
> How about everything else that was mentioned on the original pr?

Those were the two main reasons, were they not?

**Comment by BongaTheProto** [comment]
> > How about everything else that was mentioned on the original pr?
> 
> Those were the two main reasons, were they not?

"Emagged minesweeper is the strongest bomb in the game. Each individual mine is a (0,2,3) explosion. Each mine. The more mines, the more explosions. A failed emagged minesweeper ends a round guaranteed, for the cost of one (1) emag charge. I don't know who thought this was a good idea"

**Comment by NullFag** [comment]
> "Emagged minesweeper is the strongest bomb in the game. Each individual mine is a (0,2,3) explosion. Each mine. The more mines, the more explosions. A failed emagged minesweeper ends a round guaranteed, for the cost of one (1) emag charge. I don't know who thought this was a good idea"

A. 5-tile radius explosion originating from the machine (aka people standing near to the machine) that
B. Is visibly a danger to the player, as the emagging shows up in the main menu, that
C. Doesn't breach the hull or gib the user.

Yes, it will kill them. No, it won't round remove them. Considering how emagged Orion Trail can **literally** create a singularity, and gives a maxcap as a price, I don't see how emagged minesweeper is THAT big of an issue.

**Comment by BongaTheProto** [comment]
Yeah no, people are already complaining that it could be used for griefing even more than a singulo. Specifically people who have seen it happen in cit already

**Comment by BongaTheProto** [comment]
> Yeah no, people are already complaining that it could be used for griefing even more than a singulo. Specifically people who have seen it happen in cit already

If the emag and explosions are removed this will be merged

**Comment by NullFag** [comment]
Right, the removal PR forgot to mention the actual thing an emagged minesweeper does. AKA: Explode a bunch of random turfs nearby.

Yeah, give me a moment.

**Comment by NullFag** [comment]
Alrighty, the resulting explosions should be way less of an issue. The main one centered on the machine remains how it was though, as you SHOULD die upon fucking up.

**Comment by NullFag** [comment]
image

**Pull request closed without merging**
