### PR TITLE
Kangaroo tail.

### PR DESCRIPTION
**Pull request by Sidelizarder**
# About The Pull Request

Adds a sprite for a kangaroo tail I guess. Mainly making this pr on behalf of Scuhf.

## Why It's Good For The Game

The original kangaroo tail sprite sucks ass.

## A Port?

Nah.

## Changelog

:cl:
add: New taur sprite, Kangaroo Tail.
/:cl:

### CODE REVIEW

**Review by BongaTheProto — CHANGES_REQUESTED** [review]
You edited the shadekin taur without knowing. Please undo the changes in it

**Comment by BongaTheProto** [comment]
Wait actually... Is this supposed to be a normal tail? This doesn't look like a taur tail

**Comment by BongaTheProto** [comment]
> > Wait actually... Is this supposed to be a normal tail? This doesn't look like a taur tail
> 
> Scuhf says they made it on the taur template just because the tail was SLIGHTLY, too big for the normal one.

Well it should be declared on its own tail file dmi that supports its size like the one for bigger wings or somehow put it in the normal tails file, and then declare it as a normal tail instead of a taur one because that's not gonna work properly

**Comment by Sidelizarder** [comment]
In hindsight, being 

> > > Wait actually... Is this supposed to be a normal tail? This doesn't look like a taur tail
> > 
> > 
> > Scuhf says they made it on the taur template just because the tail was SLIGHTLY, too big for the normal one.
> 
> Well it should be declared on its own tail file dmi that supports its size like the one for bigger wings or somehow put it in the normal tails file, and then declare it as a normal tail instead of a taur one because that's not gonna work properly

Aight, I may as well take a bit to try that instead of brute-forcing it a solution.

**Pull request closed without merging**
