### PR TITLE
Unlimited max age

### PR DESCRIPTION
**Pull request by LeDrascol**
# About The Pull Request
_Requested by Snips#3362
Increased by Queen Baphomet#7190
Increased again by BongaTheProto_
Increases the max age of players from 85 to ~~500~~ 16,777,216.

## Why It's Good For The Game
Original proposed reasons were:
- "i need my 250 year old dwarf" (Snips)
- "For like.... Ancient people" (Queen Baphomet)
- "Well is it possible to keep AGE_MAX with their original define and only edit the specific part that asks the player for the age so it doesn't have that limit when they introduce it?" (BongaTheProto)

## A Port?
No.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: Increased max age from 85 to 16,777,216
/:cl:

### CODE REVIEW

**Comment by BongaTheProto** [comment]
Honestly, why not just removing the age's upper limit (not the lower one) altogether, would it cause any issues at all?

**Comment by LeDrascol** [comment]
> Honestly, why not just removing the age's upper limit
New characters pick a random age. After setting AGE_MAX to INFINITY, I only receive characters aged -2.14748e+009 years old.
Completely removing AGE_MAX would require editing four other files that use it.

**Comment by BongaTheProto** [comment]
> New characters pick a random age. After setting AGE_MAX to INFINITY, I only receive characters aged -2.14748e+009 years old. Completely removing AGE_MAX would require editing four other files that use it.

Well is it possible to keep AGE_MAX with their original define and only edit the specific part that asks the *player* for the age so it doesn't have that limit when they introduce it?

**Comment by LeDrascol** [comment]
> Well is it possible to keep AGE_MAX with their original define and only edit the specific part that asks the _player_ for the age so it doesn't have that limit when they introduce it?

Unfortunately I can't figure out a way to do this while preserving modularity. The AGE_MAX value can't be changed as-needed, and I'm unsure if the required sections from the saving and loading functions can be overridden.

It may be better to submit maximum age removal upstream instead.

**Comment by BongaTheProto** [comment]
> Unfortunately I can't figure out a way to do this while preserving modularity. The AGE_MAX value can't be changed as-needed, and I'm unsure if the required sections from the saving and loading functions can be overridden.
> 
> It may be better to submit maximum age removal upstream instead.

fair

**Comment by CocaColaTastesGood** [comment]
lower the minimum age to zero so Baphomet can roleplay better.

**Pull request merged**
