### PR TITLE
[TESTMERGE ONLY] MODsuits

### PR DESCRIPTION
**Pull request by JerryWester**
### Note: This code is intended to make its way back to [Citadel](https://github.com/Citadel-Station-13/Citadel-Station-13). This PR exists only for ease of testmerging and is not planned to be exclusive to Splurt.

# About The Pull Request

Adds MODsuits and various associated modules for it

## Why It's Good For The Game

Because MODsuits are cool and fun (and most importantly, completely optional and unobtrusive)

## A Port?

Yes, primarily from [/tg/station](https://github.com/tgstation/tgstation) with snippets taken from [Skyrat](https://github.com/Skyrat-SS13/Skyrat-tg/tree/master/modular_skyrat/modules/modsuit_pai/code) and an attempted [Voidcrew port](https://github.com/voidcrew/Voidcrew-LRP/pull/430)

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: MODsuits, MODsuits, MODsuits. Construction materials, research nodes, modules, etc.
add: Broken MOD cores can be found in maintenance loot
tweak: Defibs fire a signal on a successful result
tweak: AI and pAI procs to enable MODsuit control
/:cl:

### CODE REVIEW

**Comment by JerryWester** [comment]
Here's a list of things currently functioning improperly from my own testing:
- [ ] Sprites, sprites, sprites. While the sprites look fine on plantigrade models, digitigrade and taur users will suffer.
- [ ] pAI stuff is unimplemented for the most part.
- [ ] AI can't control a modsuit while the user is downed
- [ ] Losing a limb may cause the suit to become stuck in the powered on state
- [ ] Ore bag code is completely unimplemented
- [ ] Microwave runtimes, but is otherwise functional
- [ ] Miner plating doesn't show up properly

**Comment by JerryWester** [comment]
The suits have reached a point where I've become mostly confident in their stability that I'll be marking it as ready for review. Though unfinished in places (notably using placeholder sprites for anthro overlays), I believe it to be ready for testing.

**Comment by SpookyTheFox** [comment]
I've played with it on local test, looks good Jerry! Can't wait to see it go live.

**Comment by MichaelMaCleod007** [comment]
GPS, Resin, and Constructor mods seem to not work. Also if not too much trouble I'd love the MOD Holster able to stow an RCD given it's gun like profile. I forget which version of SS13 had it but there was one where holsters that attached to clothing could hold an RCD.

**Comment by JerryWester** [comment]
> GPS, Resin, and Constructor mods seem to not work.

GPS should have been fixed (see [8055a05](https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/623/commits/8055a0517c5907be4bac9d7bf3236d6e324112f5)), constructor probably works, just not how you'd think it works, resin has been reported. Constructor is intended to have the same functionality as tinkers gloves, which is... rather underwhelming. For more information, check [this issue on the discord](https://discord.com/channels/908082639704064051/1060706242860949654/1060846274099826749).

**Comment by JerryWester** [comment]
Planned changes/fixes:
- [ ] Add paint kit to research
- [ ] Port over painting functionality from TG
- [ ] Place rescue plating in CMO locker
- [ ] Make safeguard plating and place in HoS locker
- [ ] Fix pAI "replication"
- [ ] Fix resin spray module
- [ ] Replace constructor with built-in RCD
- [ ] Fix eating/drinking triggering springlocks
- [ ] Not all suits are spaceproof?
- [ ] Pull armor values from TG

**Comment by Varston** [comment]
from my own usage, Xenobio speed potion partially works.

With the speed potion you still are slowed, not as much think it was about the same as wearing a duffle and not like a actual Eva suit

when deployed the speed potion properties didn't transfer over onto the parts so was slowed down as if wearing a duffle and eva suit again

**Pull request merged**
