### PR TITLE
removes cringe recipes

### PR DESCRIPTION
**Pull request by NullFag**

### CODE REVIEW

**Comment by BongaTheProto** [comment]
why

**Comment by NullFag** [comment]
ashies having the abiility to craft futuristic shit is just bad

**Comment by Hideyoshi1** [comment]
looks good to me - just change
sandpoot you on crack
with
Becasue ashies having futuristic tech without interacting with an actually advanced civilization is bad.

or something similar to that

**Review by Hideyoshi1 — CHANGES_REQUESTED** [review]
looks good to me - just change
sandpoot you on crack
with
Becasue ashies having futuristic tech without interacting with an actually advanced civilization is bad.

or something similar to that

**Review by Hideyoshi1 — APPROVED** [review]
Super ( -v-)b

**Comment by dragonbird13** [comment]
> ashies having the abiility to craft futuristic shit is just bad

Since it comes to that, let’s write a chat filter that will prevent ashwalkers from speaking in modern words.

If you think they all are non-rp assholes and you really want to screw up game for ashwalkers, then I ask you to write a code that will not allow crafting these things ONLY to ashwalkers.

**Comment by NullFag** [comment]
> Since it comes to that, let’s write a chat filter that will prevent ashwalkers from speaking in modern words.

But I already have.

**Comment by NullFag** [comment]
Also it's not "ashies shouldn't have it" (though that is true), it's that not even a scientist would be able to hand-craft a complex circuit board. It's basically equivalent to someone hand-crafting, say, a **modern** graphics card or similar.

But yeah, unless you find a video of someone doing exactly that I don't see why I should change my stance on this.

**Comment by dragonbird13** [comment]
> But yeah, unless you find a video of someone doing exactly that I don't see why I should change my stance on this.

We are playing a game about 2D astronauts. Here everyone can perform brain surgery, coronary bypass without any difficulty. At the same time, the medical staff is terribly incompetent in their work. Each piece of metal can assemble a chair. Anyone without special skills can assemble an mech. There is no logic.

At the same time, other players can create sheer madness, shouting about memes, making conveyors with a huge number of items, and doing things after which you are afraid to enter such a littered station. There is completely no logic.

But we also have good roleplayers. They play their role in good faith. They do what only their character can know and will never be tempted to do something different in the role-playing environment. This is the essence and pleasure of roleplayers - challenging temptation. This is the spirit of good role-play where you have many freedoms, but you make your own limits and enjoy following your principles.

Okay, if what I said above has no weight, then try asking the admins to spawn three different boards for you when you decide to play hermit in lavaland / space. 80% will ignore you, as will as your ticket.

Why did I write so much about some lousy board? Because this removal will be followed by others. Next SS13 build will have restrictions, mired in crutches. There will be no spirit of freedom and only one insipid mechanics.

**Pull request closed without merging**
