### PR TITLE
Comments out "Infectious Exo-Locomotion" program

### PR DESCRIPTION
**Pull request by IgiariValkyr**
# About The Pull Request

It's against the rules to have a mass infectious nanite program or virus anyways, so this just comments out the whole program to avoid it being used. Yes even by admins.

## Pre-Merge Checklist

- [x] You documented all of your changes.

## Changelog

:cl:
del: Removes the Infectious Exo-Locomotion nanite program
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
And since nanites aren't an upstream thing anymore at TG, no need to modularize it cause they fully removed it anyways.

**Comment by LunarFleet** [comment]
This has my approval at the least; we'll have to see what Mosley says about it though.

**Comment by zeroisthebiggay** [comment]
> And since nanites aren't an upstream thing anymore at TG, no need to modularize it cause they fully removed it anyways.

splurt's a sand downstream which's a citadel downstream which's its own codebase so nanites still exist

**Comment by LeDrascol** [comment]
Instead of commenting out the code, just modular-ly remove it from the techweb entry, or remove the harm nanites techweb node entirely.

Found here:
https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/blob/master/code/modules/research/techweb/nodes/nanites_nodes.dm#L75

**Comment by BongaTheProto** [comment]
handled by https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/762

**Pull request closed without merging**
