### PR TITLE
Borg resize fix

### PR DESCRIPTION
**Pull request by Kamatii**
## About The Pull Request

A perm fix for my temp fix earlier. And with some new stuff added!

## Why It's Good For The Game

Admin resize, borg panel, or shrink and expand upgrades or any type of resize for borgs now should work fine.
Added a new feature, you can set custom size for your borgs! use expander or shrinker in hand and set the custom size before you plop it inside the borg, to go back to normal size reset the borgs.

## A Port?

no

## Changelog
:cl:
fix: fixed update_transform for silicon, they now resize properly and stay on floor
add: in-hand use borg expander and shrinker to give custom size, then insert to apply the resize, reset the to get the default size back
/:cl:

### CODE REVIEW

**Comment by BongaTheProto** [comment]
Think you could modularize the new class var and proc declarations on their own modular_splurt/code/game/objects/items/robot/robot_upgrades.dm file?

**Comment by Kamatii** [comment]
@BongaTheProto .w. like this?

**Comment by BongaTheProto** [comment]
uuhhh kind of but there was no need to move everything, only the proc you declared and the variables

**Comment by BongaTheProto** [comment]
there we go, upstream updated the repo so I recommend you check the code to make sure it still works the way you wanted to

**Comment by Kamatii** [comment]
uwu sorreh was busy, checked it, had to change a few things, works nicely now x3

**Pull request merged**
