### PR TITLE
its not necrophilia if they say yes....

### PR DESCRIPTION
**Pull request by Moribun**
*brought zombies down to a uniform baseline across all species

*low-light vision, space-proof, no soft crit and they take 20% more damage and move 10% slower

*added brainlover trait to zombies specifically which makes them heal from eating brains

*added Brain Mush as a chem. heals zombies causes ever so light tox damage to normals

*tweaked brain related foods to have brain mush in them. also made brains edible if player has BRAINLOVER trait. tested to make sure no surgery conflicts happened

*also made a soup for them with a sprite

# About The Pull Request

its unfucking zombies that was left unfinished and had them being incredibly too species specific for there unique whatever the person planned. no damn reason an undead lizard should take REDUCED damage while the mammal took increased damage. this brought them all in line to be uniformly the same and less painful to play

## Why It's Good For The Game
I dont know figure it out yourself.
## A Port?
no, I stripped some code from my own base for the chem but thats it

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: brain mush. new chem for zombies
add: new trait brainlover specific to zombies to heal off brain mush

tweak: zombie stat's across the board to be space resistant, move 10% slower and take 20% more damage
balance: zombies as a whole

/:cl:

### CODE REVIEW

**Comment by zeroisthebiggay** [comment]
making brains physically unable to be consumed nor destroyed has been a balance concern on tg `(where this codebase derives)` since the dawn of time. the rare exception is brain burgers for some unknown reason

letting players consume another player's very consciousness with ease both intentionally and accidentally only serves to cause issue in the long term when it comes to keeping people in the round; you never know when you'll accidentally click on yourself when trying to stick someone's brain into a cloner only to render them permadead because organs with chunks taken out of them generally don't work the best

iirc romerol zombies on certain codebases have the ability to devour brains through special interactions so if anything i'd keep consuming the brain entity itself either not possible or restricted to undead mobs specifically.

**Comment by zeroisthebiggay** [comment]
> `words`

that's a fair comprimise

**Comment by Ghostcoffeee** [comment]
From what I can see, only the U-lizards have the cold resist trait, while the others don't

**Comment by Moribun** [comment]
> From what I can see, only the U-lizards have the cold resist trait, while the others don't

was an oversight its fixed

**Comment by Moribun** [comment]
> From what I can see, only the U-lizards have the cold resist trait, while the others don't

was an oversight its fixed

**Comment by SpookyTheFox** [comment]
I'd prefer they had some balance mechanic other than making them slightly slower, because that's how people want to "balance" everything and all it really does is make the experience a drain on the player when it's already a laggy experience
making all the zombie races in line stats wise so the lizard one doesn't have an outsize advantage is all good, but why make them all space proof and with night vision and also not get critted, which basically gives them double health?
that's like.... a lot of stuff to get for free

**Comment by Moribun** [comment]
> I'd prefer they had some balance mechanic other than making them slightly slower, because that's how people want to "balance" everything and all it really does is make the experience a drain on the player when it's already a laggy experience making all the zombie races in line stats wise so the lizard one doesn't have an outsize advantage is all good, but why make them all space proof and with night vision and also not get critted, which basically gives them double health? that's like.... a lot of stuff to get for free

cut lizards taking reduced damage, added low light the insect got, they all already had space proof to begin with made it cleaner, reduced the overall slow down that was at 30% slow down at its lowest originally down to 10% across the board. short answer combined all there shit across the board, reduced the overall slowdown to be less painful and made them take increased damage. im not gonna play devils advocate for overall balance considering this is predominately an RP server and it shouldnt be an issue regardless. you realize before I even touched this they couldnt get critted and was space proof...all of them.

**Pull request closed without merging**
