### PR TITLE
Gargoyle Stat Panel Info

### PR DESCRIPTION
**Pull request by JerryWester**
# About The Pull Request

Replaces the check energy action with stat panel info

preview

## Why It's Good For The Game

Reduces button bloat

## A Port?

Nope

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added stat panel info for gargoyle trait
del: Removed check energy action for gargoyle
tweak: Gargoyle energy now caps out at 100
tweak: Add trait define to gargoyle quirk
fix: Fixed being able to use preserve while transformed
fix: Fixed a small runtime with remove
code: Fixed a small typo
/:cl:

### CODE REVIEW

**Comment by JerryWester** [comment]
Drafting until #664 gets merged or closed

**Comment by Seris02** [comment]
I'll just put down what I put on discord here as well, since it'll totally get buried in discord, why I don't think this should happen

> I thought about adding the energy n stuff to the stat panel, but couldn't think of a code efficient way
> it'll just make the server lag more because it's going through however many traits/quirks the mob has every time it has to update the stat panel
> for every human mob
> it'll only be a little bit more lag but it adds up

button bloat is better than lag imo

**Comment by BongaTheProto** [comment]
Instead of putting it in the status panel, why don't you add it to the mob examine?

**Comment by Seris02** [comment]
> Instead of putting it in the status panel, why don't you add it to the mob examine?

uhhhh a few problems with that but mostly
can't click yourself while being gargoyle/in a locker/many other things

**Comment by funnyfreeperson** [comment]
could you make it so that gargolyes can be interacted with while being a statue and nude? kinda annoying and no power perversion potential without, also it's really weird that being deconstructed or broken while being a statue doesn't kill you. at the very least it should kill you

**Pull request closed without merging**
