### PR TITLE
Cog Changes

### PR DESCRIPTION
**Pull request by AshTheDerg**
Cog, new and improved! No more shitty router that doesn't even work!

# About The Pull Request
A rework of CogStation, including Perma Brig and removal of Router System that didn't even work.

## Why It's Good For The Game
Cog is a staple of SS13, it's been a long time coming to fix it.

## A Port?
No.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
fix: CogStation
/:cl:

### CODE REVIEW

**Comment by battlestar-gafraktika** [comment]
i know the router system wasn't great and all, but why did you remove the transport tube into telecomms? the new hallway just looks tacked on and unsightly, same for the hallway leading into perma-brig, which you can definitely make shorter.

before
image

after
image

permabrig
image

**Comment by battlestar-gafraktika** [comment]
image
also, isn't this space meant to also function as a perma-brig, with temporary prisoners mixed in with perma-brig prisoners? what's wrong with it & if it's not the perma anymore, are you going to make any changes to it?

**Comment by AshTheDerg** [comment]
I removed the tube due to issues. Plus, it's easier to drag a crate down a hallway.

Perma's hallway is fine. If anything, it needs decoration.

I'm not touching Gen-Pop. It'll stay as regular holding.

**Comment by battlestar-gafraktika** [comment]
> I removed the tube due to issues. Plus, it's easier to drag a crate down a hallway.
> 
> Perma's hallway is fine. If anything, it needs decoration.
> 
> I'm not touching Gen-Pop. It'll stay as regular holding.

what issues? is being able to drag a crate down the hallway (which you dont and/or won't do a whole lot going there anyway) worth putting a brick where the tube used to be?

i mean, decoration could help, but its the fact that its incredibly out-of-the-way and sticking out from the rest of the map makes it look bad. i've seen worse, but this still kind of sucks. what you could do instead is to remove/move the advanced interrogation room & the hallway leading into it, and replace the hallway with the permabrig entrance

sure, but what was wrong with genpop to justify splitting it off into two seperate perma & temporary areas?

**Pull request merged**
