### PR TITLE
[READY] Yeah its a lotta things again

### PR DESCRIPTION
**Pull request by BongaTheProto**
# About The Pull Request
I will be adding lots of new content wooohooo!!
It appears it wasn't as much as I thought

## Why It's Good For The Game
idk

## A Port?
tempt, vice, hyper and skyrat
Credits to [Arctaisia](https://github.com/Arctaisia)  for the gremlin sprites and @[SquishyRolls](https://github.com/quotefox/Hyper-Station-13/commits?author=SquishyRolls) for the racc sprites

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Rest and drag yourself into a table to crawl under it
add: "Spooky" element to make things spooky
add: PDA function for borgs
add: Tau and Smolstation updates
imageadd: adds new body markings
imageadd: New gremlim style
fix: Jumpsuits no longer spawn unders... I think
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
HE DID IT AGAIN

**Comment by Arctaisia** [comment]
If you're going to be taking my gremlin sprites, as well as toonclyde's gremlin sprites, can you at least properly credit what work we did?

**Comment by Dahlular** [comment]
You've not been crediting my PRs and work from Hyperstation for a while either, but I doubt you give a whole shit about it.
Please at least credit properly.

**Comment by BongaTheProto** [comment]
> You've not been crediting my PRs and work from Hyperstation for a while either, but I doubt you give a whole shit about it. Please at least credit properly.

bro?
image
image

**Comment by Arctaisia** [comment]
I myself, am talking about this PR and the last PR, https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/293, both of which just say 'Hyper' and have no credit towards the creators of any of the ports, nor do they have GitHub links to their respective PRs from each server.

**Comment by TotallyNotADog** [comment]
> > You've not been crediting my PRs and work from Hyperstation for a while either, but I doubt you give a whole shit about it. Please at least credit properly.
> 
> bro? image image

This is a shitty joke right? I refuse to believe I share a planet with someone who thinks giving credit to something is quoting something else from 3 months ago

**Comment by NopemanMcHalt** [comment]
### Welcome to asset copyright hell.
You all have a point, but it would be more appreciated to link to your original PRs in the comments, so maintainer porting them could actually credit you accurately in the related PRs/code, as well give you a pardon. ~~(though sometimes some people don't deserve a sorry)~~

Or, of course, you can just continue jumping on the throat about it and not provide any links. Guess that works too.
Yes, I am a retarded, ass-hole contributor, how do you know?

**Pull request merged**
