### PR TITLE
[BOUNTY] That one awful vile bounty sent by the antichrist himself to make me suffer, part 1 - Genital manager TGUI

### PR DESCRIPTION
**Pull request by ChungusGamer666**
# About The Pull Request

In order to not go insane, i am splitting https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/issues/299 into several workable PRs.
This is the simplest - and least degenerate - part of that ungodly abomination of a bounty, the genital manager.

## Why It's Good For The Game

It's not.

## A Port?

No. I'm better than Sandpoot.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Genital manager menu.
del: Redundant verbs that now have been moved to the genital manager tgui.
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
how do i tun this into a draft

**Comment by BongaTheProto** [comment]
Under reviewers on the right

**Comment by remis12** [comment]
This code is good 🤓 🤓 🤓  but...Erm... 🤓 🤓 🤓 Where's the sounding, dude. 🤓 🤓 🤓

**Comment by LunarFleet** [comment]
inb4 this doesn't work with borgs, and borg players around the globe sob

**Pull request closed without merging**
