### PR TITLE
Content overhaul

### PR DESCRIPTION
**Pull request by MosleyTheMalO**
# About The Pull Request
Wow! I found a bag of content on the side of the road on my way home, it was full of new things that I could add to the station and epic improvements! I don't know who could've coded it but I guess they just wanted me to grab it! Can you believe it guys?
Some of the content this pr adds:

- New sprites for floors, doors and items
- New space ruins
- Edits to several simplemobs and mechanics
- Varying maintenance for box station
- some new hotel rooms

## Why It's Good For The Game
Adds a bunch of improvements and new content for our server

## A Port?
From venus lol.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: New infinidorm rooms
add: New random templates for boxtation's maints
add: New space ruins
tweak: several edits to simplemobs such as seeing their health
imageadd: TG sprites for doors, floors and other items
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
Stole a bunch of shit from a superior fork award 🎖️

**Comment by ChungusGamer666** [comment]
To every gooner seeing this:

Stop playing on parasites, go to the host
https://github.com/VENUS-Station/VENUS-Station-13

**Comment by NopemanMcHalt** [comment]
> To every gooner seeing this:
> 
> Stop playing on parasites, go to the host https://github.com/VENUS-Station/VENUS-Station-13
> 
> https://discord.gg/kCuWJRdzb7

Please, ask VENUS to update their `README.md` to include proper Discord link instead of it going to SPLURT per default. And maybe don't include kofi and patreon links to non-existent/false-leading links.
Also, didn't you know most if not all open-source projects are essentially parasites?

~~oh and chungus is a ██████~~

Sincerely,
Retarded Man.

**Comment by ChungusGamer666** [comment]
> Also, didn't you know most if not all open-source projects are essentially parasites?
> 

Yes, but sue to reasons which Goku will announce at some point, this is a special case of scumbaggery. Mosley essentially sacked Goku as a maintainer for petty reasons only to snatch basically everything from his own fork.

**Pull request merged**
