### PR TITLE
New horns to use

### PR DESCRIPTION
**Pull request by lolman65**
## About The Pull Request

NEW HORNS! to use and have custom horns.. more reminiscent of a bull.

## Why It's Good For The Game

it aint.

## Changelog
:cl:
add: Added demon horns
/:cl:

### CODE REVIEW

**Comment by PhoronRestructurantHuman** [comment]
That's really gamer, my homie!

**Comment by lolman65** [comment]
> That's really gamer, my homie!

what.

**Comment by BongaTheProto** [comment]
> > That's really gamer, my homie!
> 
> what.

it's cool

**Comment by lolman65** [comment]
thanks!

**Review by lolman65 — COMMENTED** [review]
ahhh, thats how it looks to modularize.

**Pull request merged**
