### PR TITLE
[NON-MODULAR] [TM ONLY] Supercruise

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

Ports supercruise from beestation!! This heavily overhauls how space travel works, making shuttles fly between locations instead of just "jumping" between them. It also allows for infinite amount of ruins, loading ruins when a player enters, and unloading ruins when all players leave the area.

## Why It's Good For The Game

This change is part of my Master Plan to provide more off-station opportunities for more action bullshittery, instead of being constrainted to the station. Because, sometimes, people aren't horny.

This will be followed by adding some "static" ruins, which aren't unloaded - for locations such as the old crew and potentially some functional outposts for players to use.

## A Port?

Obviously. A lot of stuff has been cut from the original change, due to balancing being very different here. Hopefully I can make something out of it. https://github.com/BeeStation/BeeStation-Hornet/pull/4543

## Changelog
:cl:
add: Added supercruise, overhauling shuttle movement
/:cl:

### CODE REVIEW

**Comment by jbox144** [comment]
right, this still has some work...

Need to fix the maps and such. It works just fine, but the checks don't like it, naturally.

**Comment by jbox144** [comment]
arghhh

**Comment by jbox144** [comment]
I NEED SOME HALP

**Comment by jbox144** [comment]
and gud

**Comment by BongaTheProto** [comment]
Ok so, this is now as modularized as it could be now. I ran some tests and everything seems to work as intended. However, please double check that everything's working as it is supposed to.

**Pull request closed without merging**
