### PR TITLE
Cargonia gambling update

### PR DESCRIPTION
**Pull request by Zeddersds**
# About The Pull Request
 
Lets cargonia and anyone have chance to gamble 1 million from abandoned crate with 1% chance, as well adds new cryptominer thats locked behind new technode.

## Why It's Good For The Game

New crypto and chance become millionaire if you lucky.

## A Port?

Nuh uh

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Zeddersds** [comment]
Since i was yeeted from discord server for no reason here is my discord if you wanna contact with me : atlas5138

**Comment by BongaTheProto** [comment]
Why was this closed?

**Comment by Zeddersds** [comment]
Also i wanted to try make abandoned crates to not explode but if you remove boom proc you can open them just clicking by any object that isn't multitool and need alternative so you can't break it open either

**Comment by Zeddersds** [comment]
Actually hold up lemme make new pull request since my fork was deleted by me oops

**Pull request closed without merging**
