### PR TITLE
Adds a shock collar kit to the loadout

### PR DESCRIPTION
**Pull request by battlestar-gafraktika**
# About The Pull Request

Adds a box containing a shock collar & a signaler to the loadout screen, under the Backpack - Toys category.

It costs 3 points.

image

image

## Why It's Good For The Game

You can now spawn with a shock collar, regardless of access to a kinkmate, and now don't have to raid a kinkmate to get one.

## A Port?

Code is original.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: New Silver Love Co. Shock Collar Kit Box.
add: The above is also in the loadout screen.
/:cl:

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
3 points bro? Dump that shit down to 1

**Comment by battlestar-gafraktika** [comment]
> 3 points bro? Dump that shit down to 1

It's a bundle of two items, both with a function, both being somewhat limited in supply on-station. If anything, it should cost more.

**Comment by The-Sun-In-Splendour** [comment]
> > 3 points bro? Dump that shit down to 1
> 
> It's a bundle of two items, both with a function, both being _somewhat_ limited in supply on-station. Cost is fine.

"Somewhat limited" you can get an infinite amount from infinidorms.

**Comment by BongaTheProto** [comment]
Is this pr gonna be continued?

**Comment by battlestar-gafraktika** [comment]
> Is this pr gonna be continued?

it's done, someone just needs to merge it

**Comment by BongaTheProto** [comment]
> it's done, someone just needs to merge it
there's merge conflicts that need to be resolved

**Comment by battlestar-gafraktika** [comment]
whenever i get around to it then

**Pull request merged**
