### PR TITLE
CogStation Remake

### PR DESCRIPTION
**Pull request by JWosak**
# About The Pull Request
Remake of Cogmap 1 built to fit the server and look like other maps in rotation like BoxStation, DeltaStation, MetaStation while combining designs of multiple Goonstation maps such as: Cogmap 1, Cogmap 2, Oshan Laboaratory, Kondaru, expands on departments and maintenance with a lot of QOL with a lot of buttons and shutters.

Note: I have play tested this map many times and i haven't found anything to correct, so this should be finished product, but i might have missed something, this map will still get active updates and corrections upon found problems.

## Why It's Good For The Game

Due to current CogStation version being old Goonstation version of map, I have updated it to current Cogmap 1 version and then modified it to fit the server. People who playtested it and looked over the screenshots gave mostly positive reviews that it is better and looks better too, only part that some peole did not like was kitchen and botany being too far, but that is very similar to original and i had no idea how to change it to better without compromising looks. I put a lot of time into decals and details to try give the map more life than being just gray floor. Screenshots trough development can be found on mapping channel on Discord, if you cannot find such thing then you are on wrong Discord server or this is PR to wrong codebase,

## A Port?

"Cogmap 1" (Goonstation)

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes. (Too many changes for them all to be documented)

## Changelog

:cl:
del:

- CogStation

add:

- CogStation
- Ai Laws Conf.mark included
- Designation Tag Conf.mark included

tweak:

- Perma is now perma + genpop

- Atmos moved

- Supply and Scrubbers network now use layers

- Engineering moved

- Engine is now SM

- Cargo moved

- T-comms moved

- AI sat has been merged with science

- Robotics moved

- Blueshield office is now connected to bridge

fix: 

- Turbine now has console

expansion:

- Expanded dorms

qol: 

- Added more privacy shutters

/:cl:

### CODE REVIEW

**Review by BongaTheProto — CHANGES_REQUESTED** [review]
Please save your map in TGM format using SDMM, and install the git hooks in tools/hooks/install.bat

**Comment by JWosak** [comment]
> Please save your map in TGM format using SDMM, and install the git hooks in tools/hooks/install.bat

File should now be in TGM format, as for git hooks, I had no idea how to proceed with that, so I downloaded newest version and installed it and then opened tgstataion.dme in SDMM and did changes in file

**Comment by BongaTheProto** [comment]
> File should now be in TGM format, as for git hooks, I had no idea how to proceed with that, so I downloaded newest version and installed it and then opened tgstataion.dme in SDMM and did changes in file

Just go in your pc to the folder I mentioned in the repo and run install.bat

**Comment by JWosak** [comment]
> > File should now be in TGM format, as for git hooks, I had no idea how to proceed with that, so I downloaded newest version and installed it and then opened tgstataion.dme in SDMM and did changes in file
> 
> Just go in your pc to the folder I mentioned in the repo and run install.bat

I did

**Comment by JWosak** [comment]
These last few updates are for something i missed, should pass all checks again, on other note, last time there were warnings about Node.js 16 actions being deprecated and to update them to use Node.js 20 actions/checkout@v3, actions/cache@v3, actions/upload-artifact@v3

**Pull request merged**
