### PR TITLE
Pubbystation Rework

### PR DESCRIPTION
**Pull request by chefferz**
Pubbystation Rework.

Redoes dorm area to add additional dorm rooms.
Removes pool to change to sauna, also adds boxing ring.
Moves Blueshield office to beside bridge, where it should have been.
Adds a night/strip club that is below holodeck area.
Adds a dare dice room to the northwest of station.
Adds garbage disposal system to the chapel area since it was missing garbage chutes.
More hotdogs and cum.

Tested locally, will need feedback of any possible errors, but stability has been tested and most functions/AI visibility/doors should be working. 

pubby5
pubby4
pubby3
pubby2
pubby1

See pictures attached.

### CODE REVIEW

**Review by chefferz — COMMENTED** [review]
Updated to fix minor issues, v1.02

**Comment by chefferz** [comment]
Fixed some issues, needs to be updated.
--
Fixes broken atmos in one room.
Fixes some loose items that were in places
Fixes a merge conflict reported on the discord in medbay
Fixes messed up arcade machine that was giving the old xmas tree loot
Minor tweaks to blueshield and strip club area to make it flow better.

**Comment by chefferz** [comment]
V1.03, minor fixes just pushed.

Door names were incorrect in some areas (including old one in xenobio)
Mapped a walkway to chapel vs. the terrible transit tube.

**Comment by chefferz** [comment]
V1.04 minor updates just pushed.

Expands bathroom stalls by 1 square
Adds a seat to the strip club bar
Fixes some area mapping
Adds shielding to the dorms area from space dust.

**Comment by chefferz** [comment]
V1.05

Holodeck issue fixed.

**Comment by chefferz** [comment]
V1.06

Added 4 more dorms to the bottom right with shielding.
Tweaked dorm layout a little bit.

**Comment by chefferz** [comment]
v 1.07
Fixed a stupid mistake with disposals made
Reshuffled maint around disposals because it had to be moved.

**Comment by chefferz** [comment]
v1.08
Fixed tile missing under blueshield door
Staggered dorms just a little to give it a less "blocky" feel.

**Comment by chefferz** [comment]
v1.09

Fixes a wrong area
Fixes a doublestack of doors 
Fixes a stray light

**Comment by NopemanMcHalt** [comment]
This looks a little... ***Off***.
---
image

**Comment by BongaTheProto** [comment]
please fix the merge conflicts

**Pull request merged**
