### PR TITLE
makes autodocs boards not printable 

### PR DESCRIPTION
**Pull request by NullFag**
## About The Pull Request

Comments the autodoc design out.

## Why It's Good For The Game

More interactions between people, less powergame, why were they added in the first place.

## A Port?

No.

## Changelog
Doesn't work.

### CODE REVIEW

**Comment by Hideyoshi1** [comment]
The commenting out of the code is done properly (for the research nodes and for the techfabs) - and it doesn't remove the autodoc entirely - just as a researchable and printable item.

What the autodoc is for reference: a machine that you can insert organs into and have it replace them for the person placed inside.

**Review by Hideyoshi1 — APPROVED** [review]

**Comment by StrangeWeirdKitten** [comment]
What behavior with the autodoc warrants a soft removal from the game? It's a fancy research item that people would have to craft like a lot of fancy research items that improve quality of life. I really dislike removal for the sake of removal "interaction" because you will always have the wordless "here's a shot and leave" type of doctors. Especially if medical is dealing with a lot of people. 

I see that it's under advanced surgery. Perhaps instead of soft removing it, it should be moved further up the tech web such as Experimental Surgery.

**Comment by NullFag** [comment]
> What behavior with the autodoc warrants a soft removal from the game? It's a fancy research item that people would have to craft like a lot of fancy research items that improve quality of life.


Short answer: It's broken.

Long answer: Getting augmented organs was always a dance between two people. You get better performance out of yourself and in some cases, more abilities you can perform. (cough cough, alien organs, divine cords, augments) at little to no cost. Yeah sure, augments will fail if EMP'd. News flash, barely anyone carries an Ion gun on them as it can't be easily stored. However on the flipside, you can't get these implanted by yourself. You have to trust someone to put these in you, without just reporting you to sec or similar. As such, getting fully augmented as, say, an assistant is quite hard. That balance not only dampers powergaming, but it additionally provides something for medical doctors to do, as well just.. yeah. Interaction. 
And autodocs completely fuck that balance up. Why bother with convincing someone that yes, you won't murder the whole security, when you can just use an autodoc and be done? Why should doctors bother with organ manipulation surgery when they can just throw someone in an autodoc? Or better yet, just tell them to do so themselves. 


> I see that it's under advanced surgery. Perhaps instead of soft removing it, it should be moved further up the tech web such as Experimental Surgery so it's more later in the game that people actually get it.

If it's to be researchable, it'd need to be at LEAST alien surgery - and I'm hesitant even towards that since alien tech is researched in quite many rounds. Autodocs are just simply way too powerful to be obtainable every round.

> If you want to encourage more interaction or mechanics, I suggest we follow modern TG and remove cloning. Make revivals based completely on surgery, defibs, and organ decay instead of throwing a person inside a cloning pod.

I'd do it if that idea wasn't as controversial as for example,  "removing kinkmates".

**Comment by StrangeWeirdKitten** [comment]
> > What behavior with the autodoc warrants a soft removal from the game? It's a fancy research item that people would have to craft like a lot of fancy research items that improve quality of life.
> 
> Short answer: It's broken.
> 
> Long answer: Getting augmented organs was always a dance between two people. You get better performance out of yourself and in some cases, more abilities you can perform. (cough cough, alien organs, divine cords, augments) at little to no cost. Yeah sure, augments will fail if EMP'd. News flash, barely anyone carries an Ion gun on them as it can't be easily stored. However on the flipside, you can't get these implanted by yourself. You have to trust someone to put these in you, without just reporting you to sec or similar. As such, getting fully augmented as, say, an assistant is quite hard. That balance not only dampers powergaming, but it additionally provides something for medical doctors to do, as well just.. yeah. Interaction. And autodocs completely fuck that balance up. Why bother with convincing someone that yes, you won't murder the whole security, when you can just use an autodoc and be done? Why should doctors bother with organ manipulation surgery when they can just throw someone in an autodoc? Or better yet, just tell them to do so themselves.
> 
> > I see that it's under advanced surgery. Perhaps instead of soft removing it, it should be moved further up the tech web such as Experimental Surgery so it's more later in the game that people actually get it.
> 
> If it's to be researchable, it'd need to be at LEAST alien surgery - and I'm hesitant even towards that since alien tech is researched in quite many rounds. Autodocs are just simply way too powerful to be obtainable every round.
> 
> > If you want to encourage more interaction or mechanics, I suggest we follow modern TG and remove cloning. Make revivals based completely on surgery, defibs, and organ decay instead of throwing a person inside a cloning pod.
> 
> I'd do it if that idea wasn't as controversial as for example, "removing kinkmates".

Sounds reasonable

**Pull request closed without merging**
