### PR TITLE
Sentient Mobs by Sentience Potions will now receive an indicator

### PR DESCRIPTION
**Pull request by KeplerWasTaken**
# About The Pull Request
Some people were having issues role playing as sentient mobs, as sometimes their choices were marked for death due to their nature. To help them out, this heart indicator will help players and let them know that they're not regular mobs :)

## Why It's Good For The Game
Helps promote RP for the people wanting to play as mobs, avoiding (or at least hopefully lessening) situations where they get killed because they thought they were not sentient

## A Port?
No

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
qol: Sentient Mobs made by the sentience potion from xenobiology now get a cute little heart!
qol: Don't worry, mind-transfer potions too will let you have that cute heart!
/:cl:

### CODE REVIEW

**Comment by BongaTheProto** [comment]
Honestly, it would be better to give it to any simple mob that has a client in it. Would help a lot for deathclaws

**Comment by KeplerWasTaken** [comment]
I will look into it, I just fear that it might not be so easy
I will also add mind transfer potion here if I can't manage to make all mobs with a client in it have the heart
By the way, it should be noted, that the heart is the blood brother heart, if there's another icon you'd like me to use let me know :>

**Comment by KeplerWasTaken** [comment]
I think keeping it to just sentient potions and mind swap will be okay for now, I can take a look into making all mobs having this icon, and adding a way to enable/disable it, but I have some other things I want to look at :>

**Comment by zeroisthebiggay** [comment]
> I think keeping it to just sentient potions and mind swap will be okay for now, I can take a look into making all mobs having this icon, and adding a way to enable/disable it, but I have some other things I want to look at :>

keeping it that way is probably the best
admins sentient mobs for combat events a lot

**Pull request merged**
